print("REGLAS DEL JUEGO: SCRABBLE")
print("---------------------------")
print("1. Scrabble es un juego de palabras entre 2 a 4 jugadores.")
print("2. Cada jugador recibe 7 fichas con letras al inicio del juego.")
print("3. El objetivo es formar palabras sobre el tablero para ganar puntos.")
print("4. Las palabras deben colocarse en horizontal o vertical, como en un crucigrama.")
print("5. Cada letra tiene un valor en puntos; algunos casilleros del tablero multiplican el valor.")
print("6. Al colocar una palabra, se suman los puntos de cada letra más los bonos del tablero.")
print("7. Los jugadores reponen sus fichas después de cada turno.")
print("8. Gana quien obtenga más puntos cuando ya no quedan fichas para jugar.")
print("9. No se permiten palabras inventadas; se debe usar un diccionario oficial.")
print("10. Si un jugador pasa su turno 6 veces seguidas, el juego termina.")